# Generated by Django 4.1.5 on 2023-01-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
