# Generated by Django 4.1.5 on 2023-01-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded_time',
            field=models.TextField(),
        ),
    ]
