# Generated by Django 4.1.5 on 2023-01-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
