# Generated by Django 4.1.5 on 2023-01-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_submitter_photo_uploaded_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
